# ========================================
# 개발 환경 전용 설정
# Docker Compose 지원 및 디버깅 활성화
# ========================================

spring:
  # JPA 개발 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발시 스키마 자동 업데이트
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
  
  # DevTools 설정
  devtools:
    livereload:
      enabled: true     # 라이브 리로드 활성화
    restart:
      enabled: true     # 자동 재시작 활성화

  thymeleaf:
    cache: false        # 개발 환경 템플릿 캐시 비활성화

# 개발 환경 로깅 설정 - 루트 프로파일에서 상속
logging:
  level:
    root: info

# 개발 환경 서버 설정
server:
  # 에러 출력 설정 (개발시 상세 정보 표시)
  error:
    include-message: always           # 에러 메시지 포함
    include-binding-errors: always    # 바인딩 에러 포함
    include-stacktrace: on-param      # 파라미터 요청시 스택트레이스 포함
    include-exception: true           # 예외 정보 포함
  
  # 톰캣 Access Log (개발 환경에서만 활성화)
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %u %t \"%r\" %s %D"  # IP 사용자 시간 "요청" 상태코드 처리시간
      directory: logs
      prefix: access
      suffix: .log

# 개발 환경 애플리케이션 설정
boardhole:
  # 개발 환경 CORS 설정 (로컬 호스트 허용)
  cors:
    allowed-origins: "http://localhost:8080,http://127.0.0.1:8080,http://localhost:3000"
